/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JPanel;
import view.Mantenimientos.ConsultaPorCliente;
import view.Mantenimientos.ConsultaPorPedido;
import view.Mantenimientos.MantenimientoClientes;
import view.Mantenimientos.MantenimientoEmpleado;
import view.Mantenimientos.MantenimientoPedidos;
import view.Mantenimientos.MantenimientoProductos;

public class InterfazPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(InterfazPrincipal.class.getName());
    private javax.swing.JPanel panelOriginal;
    private InterfazPrincipal ventana;

    /**
     * Creates new form InterfazPrincipal
     */
    public InterfazPrincipal() {
        initComponents();
        panelOriginal = (javax.swing.JPanel) getContentPane();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuMantenimientos = new javax.swing.JMenu();
        jMenuItemClientes = new javax.swing.JMenuItem();
        jMenuItemProductos = new javax.swing.JMenuItem();
        jMenuItemEmpleados = new javax.swing.JMenuItem();
        jMenuItemPedidos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        PedidoPorClienteMenu = new javax.swing.JMenuItem();
        DetalleMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de pizzeria");

        jMenuMantenimientos.setText("Mantenimientos");

        jMenuItemClientes.setText("Clientes");
        jMenuItemClientes.addActionListener(this::jMenuItemClientesActionPerformed);
        jMenuMantenimientos.add(jMenuItemClientes);

        jMenuItemProductos.setText("Productos");
        jMenuItemProductos.addActionListener(this::jMenuItemProductosActionPerformed);
        jMenuMantenimientos.add(jMenuItemProductos);

        jMenuItemEmpleados.setText("Empleados");
        jMenuItemEmpleados.addActionListener(this::jMenuItemEmpleadosActionPerformed);
        jMenuMantenimientos.add(jMenuItemEmpleados);

        jMenuItemPedidos.setText("Pedidos");
        jMenuItemPedidos.addActionListener(this::jMenuItemPedidosActionPerformed);
        jMenuMantenimientos.add(jMenuItemPedidos);

        jMenuBar1.add(jMenuMantenimientos);

        jMenu1.setText("Consultas");

        PedidoPorClienteMenu.setText("Pedidos por cliente");
        PedidoPorClienteMenu.addActionListener(this::PedidoPorClienteMenuActionPerformed);
        jMenu1.add(PedidoPorClienteMenu);

        DetalleMenu.setText("Productos por categoria");
        DetalleMenu.addActionListener(this::DetalleMenuActionPerformed);
        jMenu1.add(DetalleMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 924, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 419, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PedidoPorClienteMenuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PedidoPorClienteMenuActionPerformed
        ConsultaPorCliente panelconsulta1 = new ConsultaPorCliente(ventana);
        setContentPane(panelconsulta1);
        revalidate();
        repaint();
    }// GEN-LAST:event_PedidoPorClienteMenuActionPerformed

    private void DetalleMenuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_DetalleMenuActionPerformed
        ConsultaPorPedido panelClientes = new ConsultaPorPedido(ventana);
        setContentPane(panelClientes);
        revalidate();
        repaint();
    }// GEN-LAST:event_DetalleMenuActionPerformed

    private void jMenuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItemClientesActionPerformed
        MantenimientoClientes panelClientes = new MantenimientoClientes(ventana);
        setContentPane(panelClientes);
        revalidate();
        repaint();
    }

    public void volverPrincipal() {
        setContentPane(panelOriginal);
        revalidate();
        repaint();
    }

    private void jMenuItemProductosActionPerformed(java.awt.event.ActionEvent evt) {
        MantenimientoProductos panelClientes = new MantenimientoProductos(ventana);
        setContentPane(panelClientes);
        revalidate();
        repaint();
    }

    private void jMenuItemEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {
        MantenimientoEmpleado panelClientes = new MantenimientoEmpleado(ventana);
        setContentPane(panelClientes);
        revalidate();
        repaint();
    }

    private void jMenuItemPedidosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItemPedidosActionPerformed
        MantenimientoPedidos panelClientes = new MantenimientoPedidos(ventana);
        setContentPane(panelClientes);
        revalidate();
        repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfazPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DetalleMenu;
    private javax.swing.JMenuItem PedidoPorClienteMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemClientes;
    private javax.swing.JMenuItem jMenuItemEmpleados;
    private javax.swing.JMenuItem jMenuItemPedidos;
    private javax.swing.JMenuItem jMenuItemProductos;
    private javax.swing.JMenu jMenuMantenimientos;
    // End of variables declaration//GEN-END:variables
}
