/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.Mantenimientos;

import dataAcces.model.Cliente;
import dataAcces.repository.Cliente_Repository;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import view.InterfazPrincipal;

/**
 *
 * @author deku
 */

public class MantenimientoClientes extends javax.swing.JPanel {

    Cliente_Repository ClienteRep = new Cliente_Repository();

    DefaultTableModel modelo;
    private MantenimientoClientes ventana;
    List<Cliente> lista;
    private javax.swing.JPanel panelOriginal;

    /**
     * Creates new form MantenimientoClientes
     */
    public MantenimientoClientes(InterfazPrincipal ventana) {
        modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Identificacion");
        modelo.addColumn("Nombre_Completo");
        modelo.addColumn("Direccion");
        modelo.addColumn("Telefono");
        modelo.addColumn("Mail");
        initComponents();
        cargarTabla();
        setVisible(true);
    }

    public void cargarTabla() {
        modelo.setRowCount(0);
        lista = ClienteRep.GetAll();
        for (Cliente cliente : lista) {
            Object[] fila = new Object[6];
            fila[0] = cliente.getID();
            fila[1] = cliente.getIdentificacion();
            fila[2] = cliente.getNombre_Completo();
            fila[3] = cliente.getDireccion();
            fila[4] = cliente.getTelefono();
            fila[5] = cliente.getMail();
            modelo.addRow(fila);
        }
        jTable1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IdentificacionTxt = new javax.swing.JTextField();
        NombreTxt = new javax.swing.JTextField();
        DireccionTxt = new javax.swing.JTextField();
        TelefonoTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BuscarIDTF = new javax.swing.JTextField();
        BotonBuscarId = new javax.swing.JButton();
        BotonInsertar = new javax.swing.JButton();
        BotonModificar = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();
        BotonActualizar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Ingrese identificacion");

        jLabel2.setText("Ingrese nombre completo");

        jLabel3.setText("Ingrese direccion");

        jLabel4.setText("Ingrese telefono");

        IdentificacionTxt.setColumns(10);

        NombreTxt.setColumns(10);

        DireccionTxt.setColumns(10);

        TelefonoTxt.setColumns(10);

        jLabel5.setText("Buscar por identificacion:");

        BuscarIDTF.setColumns(10);

        BotonBuscarId.setText("Buscar");
        BotonBuscarId.addActionListener(this::BotonBuscarIdActionPerformed);

        BotonInsertar.setText("Insertar");
        BotonInsertar.addActionListener(this::BotonInsertarActionPerformed);

        BotonModificar.setText("Modificar");
        BotonModificar.addActionListener(this::BotonModificarActionPerformed);

        BotonEliminar.setText("Eliminar");
        BotonEliminar.addActionListener(this::BotonEliminarActionPerformed);

        BotonActualizar.setText("Actualizar");
        BotonActualizar.addActionListener(this::BotonActualizarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(BuscarIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonBuscarId)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotonInsertar)
                                .addGap(18, 18, 18)
                                .addComponent(BotonModificar)
                                .addGap(18, 18, 18)
                                .addComponent(BotonEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(BotonActualizar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TelefonoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DireccionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(NombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)
                        .addComponent(IdentificacionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(IdentificacionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(NombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(DireccionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TelefonoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BuscarIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BotonBuscarId)))
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonInsertar)
                            .addComponent(BotonModificar)
                            .addComponent(BotonEliminar)
                            .addComponent(BotonActualizar))
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonInsertarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotonInsertarActionPerformed

        Cliente nuevo = construirClienteParaInsertar();
        if (nuevo == null) {
            return;
        }
        ClienteRep.Insert(nuevo);
        cargarTabla();

    }

    private void BotonModificarActionPerformed(java.awt.event.ActionEvent evt) {

        Cliente actualizado = construirClienteDesdeSeleccion();
        if (actualizado == null) {
            return;
        }
        ClienteRep.Update(actualizado);
        cargarTabla();

    }

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {

        Integer id = obtenerIdSeleccionado();
        if (id == null) {
            return;
        }
        ClienteRep.Delete(id);
        cargarTabla();

    }

    private void BotonActualizarActionPerformed(java.awt.event.ActionEvent evt) {
        cargarTabla();

    }

    private void BotonBuscarIdActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotonBuscarIdActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_BotonBuscarIdActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizar;
    private javax.swing.JButton BotonBuscarId;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton BotonInsertar;
    private javax.swing.JButton BotonModificar;
    private javax.swing.JTextField BuscarIDTF;
    private javax.swing.JTextField DireccionTxt;
    private javax.swing.JTextField IdentificacionTxt;
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JTextField TelefonoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private Cliente construirClienteParaInsertar() {
        int nuevoId = ClienteRep.GetAll().size() + 1;
        return new Cliente(nuevoId, IdentificacionTxt.getText(), NombreTxt.getText(),
                DireccionTxt.getText(), TelefonoTxt.getText(), "");
    }

    private Cliente construirClienteDesdeSeleccion() {
        Integer id = obtenerIdSeleccionado();
        if (id == null) {
            return null;
        }
        return new Cliente(id, IdentificacionTxt.getText(), NombreTxt.getText(),
                DireccionTxt.getText(), TelefonoTxt.getText(), "");
    }

    private Integer obtenerIdSeleccionado() {
        int fila = jTable1.getSelectedRow();
        if (fila < 0) {
            return null;
        }
        Object valor = jTable1.getValueAt(fila, 0);
        if (valor instanceof Integer) {
            return (Integer) valor;
        }
        if (valor instanceof String) {
            try {
                return Integer.parseInt((String) valor);
            } catch (NumberFormatException ex) {
                return null;
            }
        }
        return null;
    }

    private void rellenarCampos(Cliente cliente) {
        IdentificacionTxt.setText(cliente.getIdentificacion());
        NombreTxt.setText(cliente.getNombre_Completo());
        DireccionTxt.setText(cliente.getDireccion());
        TelefonoTxt.setText(cliente.getTelefono());
    }

    private void seleccionarEnTablaPorId(int id) {
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            Object valor = jTable1.getValueAt(i, 0);
            if (valor instanceof Integer && ((Integer) valor) == id) {
                jTable1.setRowSelectionInterval(i, i);
                return;
            }
            if (valor instanceof String) {
                try {
                    if (Integer.parseInt((String) valor) == id) {
                        jTable1.setRowSelectionInterval(i, i);
                        return;
                    }
                } catch (NumberFormatException ignored) {
                }
            }
        }
    }
}
