/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.Mantenimientos;

import dataAcces.model.Categoria;
import dataAcces.model.Producto;
import dataAcces.repository.Categoria_Repository;
import dataAcces.repository.Producto_Repository;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import view.InterfazPrincipal;

/**
 *
 * @author deku
 */

public class MantenimientoProductos extends javax.swing.JPanel {

    Producto_Repository ProductoRep = new Producto_Repository();
    Categoria_Repository categoriaRepo = new Categoria_Repository();

    DefaultTableModel modelo;
    private MantenimientoProductos ventana;
    List<Producto> lista;
    private javax.swing.JPanel panelOriginal;

    /**
     * Creates new form MantenimientoClientes
     */
    public MantenimientoProductos(InterfazPrincipal ventana) {
        modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Precio");
        modelo.addColumn("Categorias_Id");
        initComponents();
        cargarCategoriasEnCombo();
        cargarTabla();
        setVisible(true);

    }

    public void cargarTabla() {
        modelo.setRowCount(0);
        lista = ProductoRep.GetAll();
        for (Producto producto : lista) {
            Object[] fila = new Object[5];
            fila[0] = producto.getID();
            fila[1] = producto.getNombre();
            fila[2] = producto.getDescripcion();
            fila[3] = producto.getPrecio();
            fila[4] = producto.getCategoria_ID();

            modelo.addRow(fila);
        }
        jTable1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NombreTxt = new javax.swing.JTextField();
        DescripcionTxt = new javax.swing.JTextField();
        PrecioTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Buscarprecio = new javax.swing.JTextField();
        BotonBuscarId = new javax.swing.JButton();
        BotonInsertar = new javax.swing.JButton();
        BotonModificar = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();
        BotonActualizar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        CategoriaCombo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        NuevaCategoriaTxt = new javax.swing.JTextField();
        BotonAgregarCategoria = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {

                }));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Ingrese nombre");

        jLabel2.setText("Ingrese descripcion");

        jLabel3.setText("Ingrese precio");

        NombreTxt.setColumns(10);

        DescripcionTxt.setColumns(10);

        PrecioTxt.setColumns(10);

        jLabel5.setText("Buscar por ID:");

        Buscarprecio.setColumns(10);

        BotonBuscarId.setText("Buscar");
        BotonBuscarId.addActionListener(this::BotonBuscarIdActionPerformed);

        BotonInsertar.setText("Insertar");
        BotonInsertar.addActionListener(this::BotonInsertarActionPerformed);

        BotonModificar.setText("Modificar");
        BotonModificar.addActionListener(this::BotonModificarActionPerformed);

        BotonEliminar.setText("Eliminar");
        BotonEliminar.addActionListener(this::BotonEliminarActionPerformed);

        BotonActualizar.setText("Actualizar");
        BotonActualizar.addActionListener(this::BotonActualizarActionPerformed);

        jLabel6.setText("Categoria");

        jLabel7.setText("Nueva categoria");

        NuevaCategoriaTxt.setColumns(10);

        BotonAgregarCategoria.setText("Agregar");
        BotonAgregarCategoria.addActionListener(this::BotonAgregarCategoriaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(Buscarprecio, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(BotonBuscarId)))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(45, 45, 45)
                                                .addComponent(NombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(DescripcionTxt, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(CategoriaCombo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(PrecioTxt, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(NuevaCategoriaTxt, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(BotonAgregarCategoria))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(BotonInsertar)
                                                .addGap(18, 18, 18)
                                                .addComponent(BotonModificar)
                                                .addGap(18, 18, 18)
                                                .addComponent(BotonEliminar)
                                                .addGap(18, 18, 18)
                                                .addComponent(BotonActualizar)))
                                .addContainerGap(29, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(NombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(DescripcionTxt,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(CategoriaCombo,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(PrecioTxt, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel7)
                                                        .addComponent(NuevaCategoriaTxt,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(BotonAgregarCategoria)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel5)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(Buscarprecio,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(BotonBuscarId)))
                                                .addContainerGap(22, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(BotonInsertar)
                                                        .addComponent(BotonModificar)
                                                        .addComponent(BotonEliminar)
                                                        .addComponent(BotonActualizar))
                                                .addContainerGap()))));
    }// </editor-fold>//GEN-END:initComponents

    private void BotonInsertarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotonInsertarActionPerformed

        Producto nuevo = construirProductoParaInsertar();
        if (nuevo == null) {
            return;
        }
        ProductoRep.Insert(nuevo);
        cargarTabla();
    }// GEN-LAST:event_BotonInsertarActionPerformed

    private void BotonModificarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotonModificarActionPerformed
        Producto actualizado = construirProductoDesdeSeleccion();
        if (actualizado == null) {
            return;
        }
        ProductoRep.Update(actualizado);
        cargarTabla();
    }// GEN-LAST:event_BotonModificarActionPerformed

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotonEliminarActionPerformed
        Integer id = obtenerIdSeleccionado();
        if (id == null) {
            return;
        }
        ProductoRep.Delete(id);
        cargarTabla();
    }// GEN-LAST:event_BotonEliminarActionPerformed

    private void BotonActualizarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotonActualizarActionPerformed
        cargarTabla();
    }// GEN-LAST:event_BotonActualizarActionPerformed

    private void BotonBuscarIdActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotonBuscarIdActionPerformed
        String idTexto = Buscarprecio.getText();
        if (idTexto == null || idTexto.isBlank()) {
            return;
        }
        Integer id;
        try {
            id = Integer.parseInt(idTexto);
        } catch (NumberFormatException ex) {
            return;
        }
        Producto encontrado = ProductoRep.GetById(id);
        if (encontrado != null) {
            rellenarCampos(encontrado);
            seleccionarEnTablaPorId(encontrado.getID());
        }
    }// GEN-LAST:event_BotonBuscarIdActionPerformed

    private void BotonAgregarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {
        String nombre = NuevaCategoriaTxt.getText();
        if (nombre == null || nombre.isBlank()) {
            return;
        }
        int nuevoId = categoriaRepo.GetAll().size() + 1;
        Categoria nueva = new Categoria(nuevoId, nombre);
        categoriaRepo.Insert(nueva);
        cargarCategoriasEnCombo();
        seleccionarCategoriaEnCombo(nuevoId);
        NuevaCategoriaTxt.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizar;
    private javax.swing.JButton BotonAgregarCategoria;
    private javax.swing.JButton BotonBuscarId;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton BotonInsertar;
    private javax.swing.JButton BotonModificar;
    private javax.swing.JTextField Buscarprecio;
    private javax.swing.JComboBox<Categoria> CategoriaCombo;
    private javax.swing.JTextField DescripcionTxt;
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JTextField NuevaCategoriaTxt;
    private javax.swing.JTextField PrecioTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void cargarCategoriasEnCombo() {
        CategoriaCombo.removeAllItems();
        List<Categoria> categorias = categoriaRepo.GetAll();
        for (Categoria categoria : categorias) {
            CategoriaCombo.addItem(categoria);
        }
        if (CategoriaCombo.getItemCount() > 0) {
            CategoriaCombo.setSelectedIndex(0);
        }
    }

    private Producto construirProductoParaInsertar() {
        Categoria categoria = (Categoria) CategoriaCombo.getSelectedItem();
        int categoriaId = categoria != null ? categoria.getID() : 0;
        return new Producto(0, NombreTxt.getText(), DescripcionTxt.getText(),
                parsePrecio(), categoriaId);
    }

    private Producto construirProductoDesdeSeleccion() {
        Integer id = obtenerIdSeleccionado();
        if (id == null) {
            return null;
        }
        Categoria categoria = (Categoria) CategoriaCombo.getSelectedItem();
        int categoriaId = categoria != null ? categoria.getID() : 0;
        return new Producto(id, NombreTxt.getText(), DescripcionTxt.getText(),
                parsePrecio(), categoriaId);
    }

    private double parsePrecio() {
        try {
            return Double.parseDouble(PrecioTxt.getText());
        } catch (NumberFormatException e) {
            return 0d;
        }
    }

    private Integer obtenerIdSeleccionado() {
        int fila = jTable1.getSelectedRow();
        if (fila < 0) {
            return null;
        }
        Object valor = jTable1.getValueAt(fila, 0);
        if (valor instanceof Integer) {
            return (Integer) valor;
        }
        if (valor instanceof String) {
            try {
                return Integer.parseInt((String) valor);
            } catch (NumberFormatException ex) {
                return null;
            }
        }
        return null;
    }

    private void rellenarCampos(Producto producto) {
        NombreTxt.setText(producto.getNombre());
        DescripcionTxt.setText(producto.getDescripcion());
        PrecioTxt.setText(String.valueOf(producto.getPrecio()));
        seleccionarCategoriaEnCombo(producto.getCategoria_ID());
    }

    private void seleccionarCategoriaEnCombo(int categoriaId) {
        for (int i = 0; i < CategoriaCombo.getItemCount(); i++) {
            Categoria cat = CategoriaCombo.getItemAt(i);
            if (cat != null && cat.getID() == categoriaId) {
                CategoriaCombo.setSelectedIndex(i);
                return;
            }
        }
    }

    private void seleccionarEnTablaPorId(int id) {
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            Object valor = jTable1.getValueAt(i, 0);
            if (valor instanceof Integer && ((Integer) valor) == id) {
                jTable1.setRowSelectionInterval(i, i);
                return;
            }
            if (valor instanceof String) {
                try {
                    if (Integer.parseInt((String) valor) == id) {
                        jTable1.setRowSelectionInterval(i, i);
                        return;
                    }
                } catch (NumberFormatException ignored) {
                }
            }
        }
    }
}
