/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.Mantenimientos;


import dataAcces.model.Detalle_Pedido;
import dataAcces.model.Empleado;
import dataAcces.model.Pedido;
import dataAcces.model.Producto;
import dataAcces.repository.Detalle_pedido_Repository;

import dataAcces.repository.Empleado_Repository;
import dataAcces.repository.Pedido_Repository;
import dataAcces.repository.Producto_Repository;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import view.InterfazPrincipal;


/**
 *
 * @author deku
 */

public class MantenimientoPedidos extends javax.swing.JPanel {
    
    Pedido_Repository PedidoRep = new Pedido_Repository();
    Detalle_pedido_Repository PedidoDEtalleRep = new Detalle_pedido_Repository();
    
    DefaultTableModel modeloPedidos,ModeloDetalle;
    private MantenimientoPedidos ventana;
    List<Pedido> listapedido;
    List<Detalle_Pedido> listaDEPedido;
    private javax.swing.JPanel panelOriginal;

    /**
     * Creates new form MantenimientoClientes
     */
    public MantenimientoPedidos(InterfazPrincipal ventana) {
        modeloPedidos = new DefaultTableModel();
        modeloPedidos.addColumn("ID");
        modeloPedidos.addColumn("Fecha");
        modeloPedidos.addColumn("Estado");
        modeloPedidos.addColumn("Total");
        modeloPedidos.addColumn("Clientes_ID");
        modeloPedidos.addColumn("Empleado_ID");
        
        ModeloDetalle = new DefaultTableModel();
        ModeloDetalle.addColumn("ID");
        ModeloDetalle.addColumn("Cantidad");
        ModeloDetalle.addColumn("Subtotal");
        ModeloDetalle.addColumn("Pedidos_ID");
        ModeloDetalle.addColumn("Productos_ID");
        initComponents();
        cargarTabla();
        setVisible(true);
       
    }
    
    public void cargarTabla() {
        modeloPedidos.setRowCount(0);
        listapedido = PedidoRep.GetAll();
        for(Pedido pedido : listapedido){
            Object[] fila = new Object[6];
            fila[0] = pedido.getID();
            fila[1] = pedido.getFecha();
            fila[2] = pedido.getEstado();
            fila[3] = pedido.getTotal();
            fila[4] = pedido.getCliente_ID();
            fila[5] = pedido.getEmpleado_ID();
            

            modeloPedidos.addRow(fila);
        }
        jTable1.setModel(modeloPedidos);
        
        ModeloDetalle.setRowCount(0);
        listaDEPedido = PedidoDEtalleRep.GetAll();
        for(Detalle_Pedido productoDe : listaDEPedido){
            Object[] fila = new Object[5];
            fila[0] = productoDe.getID();
            fila[1] = productoDe.getCantidad();
            fila[2] = productoDe.getSubtotal();
            fila[3] = productoDe.getPedidos_ID();
            fila[4] = productoDe.getProductos_ID();

            ModeloDetalle.addRow(fila);
        }
        jTable2.setModel(ModeloDetalle);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NombreTxt = new javax.swing.JTextField();
        PrecioTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Buscarprecio = new javax.swing.JTextField();
        BotonBuscarId = new javax.swing.JButton();
        BotonInsertar = new javax.swing.JButton();
        BotonModificar = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();
        BotonActualizar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Ingrese fecha");

        jLabel2.setText("Estado");

        jLabel3.setText("Ingrese total");

        NombreTxt.setColumns(10);

        PrecioTxt.setColumns(10);

        jLabel5.setText("Filtrar por estado");

        Buscarprecio.setColumns(10);

        BotonBuscarId.setText("Buscar");
        BotonBuscarId.addActionListener(this::BotonBuscarIdActionPerformed);

        BotonInsertar.setText("Insertar");
        BotonInsertar.addActionListener(this::BotonInsertarActionPerformed);

        BotonModificar.setText("Modificar");
        BotonModificar.addActionListener(this::BotonModificarActionPerformed);

        BotonEliminar.setText("Eliminar");
        BotonEliminar.addActionListener(this::BotonEliminarActionPerformed);

        BotonActualizar.setText("Actualizar");
        BotonActualizar.addActionListener(this::BotonActualizarActionPerformed);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Completado" }));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(NombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel2))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(PrecioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(146, 146, 146)
                                        .addComponent(jLabel4))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(Buscarprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BotonBuscarId)))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BotonInsertar)
                        .addGap(18, 18, 18)
                        .addComponent(BotonModificar)
                        .addGap(18, 18, 18)
                        .addComponent(BotonEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(BotonActualizar)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(NombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(PrecioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Buscarprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonBuscarId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonActualizar)
                    .addComponent(BotonEliminar)
                    .addComponent(BotonModificar)
                    .addComponent(BotonInsertar))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInsertarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonInsertarActionPerformed

    private void BotonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonModificarActionPerformed

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonEliminarActionPerformed

    private void BotonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonActualizarActionPerformed

    private void BotonBuscarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonBuscarIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizar;
    private javax.swing.JButton BotonBuscarId;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton BotonInsertar;
    private javax.swing.JButton BotonModificar;
    private javax.swing.JTextField Buscarprecio;
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JTextField PrecioTxt;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
